### ISSUE TITLE
Support version ranges in project.json

### ISSUE THREAD

**Issue by ptrstpp950** [aspnet/KRuntime#1014] opened 2014-12-28 20:43 UTC
I am trying to force kpm restore for downloading latest nuget from feed. I did following steps:
1) I deleted everything under: `C:\Users\[user]\.kpm\packages\Newtonsoft.Json`
2) I created simple project.json file: 
```
{
    "version": "1.0.0-*",
    "dependencies": {
        "Newtonsoft.Json":""
    },
    "commands": { 
        "run" : "run"
    },
    "frameworks" : {
        "aspnet50" : { },
        "aspnetcore50" : { 
            "dependencies": {
                "System.Console": "4.0.0-beta-*"
            }
        }
    }
}
```

3) I run following commands:
-  `kpm restore`-> Newtonsoft.Json package wasn't downloaded
-  `kpm pack` -> reports an error:
```
Warning: Failed to resolve the following dependencies for target framework 'Asp.Net,Version=v5.0':
   Newtonsoft.Json

Searched Locations:
  E:\projects\aspvnext-tests\{name}\project.json
  C:\Users\garat_000\.kpm\packages\{name}\{version}\{name}.nuspec
  C:\Windows\Microsoft.NET\assembly\GAC_32\{name}\{version}\{name}.dll
  C:\Windows\Microsoft.NET\assembly\GAC_MSIL\{name}\{version}\{name}.dll

Try running 'kpm restore'.

Warning: Failed to resolve the following dependencies for target framework 'Asp.NetCore,Version=v5.0':
   Newtonsoft.Json

Searched Locations:
  E:\projects\aspvnext-tests\{name}\project.json
  C:\Users\garat_000\.kpm\packages\{name}\{version}\{name}.nuspec

Try running 'kpm restore'.
```

**Sum up**
Did I do something wrong? Or `project.json` dependencies are fixed to version number?
I tried also using `*` in version number but I cannot make it work usually having error similar to below:
`'6.0.*' is not a valid version string.`

**Comment by davidfowl** [comment] 2015-01-10 21:15
Closing this as a dupe of #442

**Closed by davidfowl** 2015-01-10 21:15 UTC
Labels: 0 - Backlog, enhancement
